export const sliderHeroData = {
  emptyMessage: "No hero slides available at the moment.",
  mainCarouselAriaLabel: "Main content carousel",
  prevButtonAriaLabel: "Previous slide",
  nextButtonAriaLabel: "Next slide",
  paginationBulletAriaLabel: "Go to slide {index}",
  firstSlideMessage: "This is the first slide",
  lastSlideMessage: "This is the last slide",
  items: [
    {
      id: 1,
      image: "/hero/hero-6.jpg",
      altText: "hero-1",
      subtitle: "Category",
      title: "Food",
      desc: "Experience exquisite dining with our gourmet dishes crafted from the freshest ingredients, designed to tantalize your taste buds.",
      link: "/menu",
      textLink: "See Our Menu",
    },
    {
      id: 2,
      image: "/hero/hero-8.jpg",
      altText: "hero-2",
      subtitle: "Category",
      title: "Cocktails & Drinks",
      desc: "Discover handcrafted cocktails and premium beverages expertly mixed to perfection, elevating your dining experience.",
      link: "/menu",
      textLink: "See Our Menu",
    },
    {
      id: 3,
      image: "/hero/hero-9.jpg",
      altText: "hero-3",
      subtitle: "Category",
      title: "Vegan",
      desc: "Savor our delicious vegan dishes made from fresh, plant-based ingredients that delight both the palate and the soul.",
      link: "/menu",
      textLink: "See Our Menu",
    },
    {
      id: 4,
      image: "/hero/hero-10.jpg",
      altText: "hero-4",
      subtitle: "Category",
      title: "Kids Menu",
      desc: "Delight your little ones with our specially crafted kids menu, featuring tasty and nutritious options that cater to young tastes.",
      link: "/menu",
      textLink: "See Our Menu",
    },
  ],
};

export const sliderHeroIntroData = {
  emptyMessage: "No hero slides available at the moment.",
  mainCarouselAriaLabel: "Main content carousel",
  prevButtonAriaLabel: "Previous slide",
  nextButtonAriaLabel: "Next slide",
  paginationBulletAriaLabel: "Go to slide {index}",
  firstSlideMessage: "This is the first slide",
  lastSlideMessage: "This is the last slide",
  items: [
    {
      id: 1,
      image: "/hero/hero-1.jpeg",
      altText: "hero-1",
      subtitle: "Category",
      title: "Beef - Restaurant Template",
      desc: "Made using only the finest coding & design practices there are, Beef - Restaurant is sure to make a perfect main ingredient for creating an irresistible your restaurant website.",
      link: "#",
      textLink: "Buy now",
    },
  ],
};
