export const galleryData = {
  subtitle: "JJ’s World",
  title: "Life at JJ’s",
  phrase: "Where every image tells the story of JJ’s atmosphere and craft.",
  divider: true,
  align: "center",
  emptyMessage: "No gallery items available at the moment.",
  errorMessage: "Error loading gallery:",
  lightboxOpenLabel: "Open lightbox",
  lightboxPrevAriaLabel: "Previous image",
  lightboxNextAriaLabel: "Next image",
  lightboxCloseAriaLabel: "Close lightbox",
  items: [
    {
      id: 1,
      image: "/gallery/gallery-27a.jpg",
      title: "Spring Roll",
      altText: "Spring Roll",
      subtitle: "Food",
    },
    {
      id: 2,
      image: "/gallery/gallery-14a.jpg",
      title: "Dinner Series",
      altText: "Dinner Series",
      subtitle: "Food",
    },
    {
      id: 3,
      image: "/gallery/gallery-15a.jpg",
      title: "Bevereges",
      altText: "Bevereges",
      subtitle: "Drinks",
    },
    {
      id: 4,
      image: "/gallery/gallery-30a.jfif",
      title: "Great Moments",
      altText: "Great Moments",
      subtitle: "Events",
    },
    {
      id: 5,
      image: "/gallery/gallery-19a.webp",
      title: "Beautiful Spaces",
      altText: "Beautiful Spaces",
      subtitle: "Locations",
    },
    {
      id: 6,
      image: "/gallery/gallery-29a.jpg",
      title: "Pleasant Spaces",
      altText: "Pleasant Spaces",
      subtitle: "Locations",
    },
    {
      id: 7,
      image: "/gallery/gallery-21a.webp",
      title: "House Recipe",
      altText: "House Recipe",
      subtitle: "Food",
    },
    {
      id: 8,
      image: "/gallery/gallery-22a.webp",
      title: "Food and Wine",
      altText: "Food and Wine",
      subtitle: "Food",
    },
    {
      id: 9,
      image: "/gallery/gallery-24a.jpg",
      title: "Pleasant Spaces",
      altText: "Pleasant Spaces",
      subtitle: "Locations",
    },
    {
      id: 10,
      image: "/gallery/gallery-25a.jpg",
      title: "House Recipe",
      altText: "House Recipe",
      subtitle: "Food",
    },
    {
      id: 11,
      image: "/gallery/gallery-26a.jpg",
      title: "Food and Wine",
      altText: "Food and Wine",
      subtitle: "Food",
    },
    {
      id: 12,
      image: "/gallery/gallery-13a.jpg",
      title: "House Recipe",
      altText: "House Recipe",
      subtitle: "Food",
    },
  ],
};
